<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LNVR_Tweaks</AssemblyName>
    <RootNamespace>LNVR_Tweaks</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <GamePath>E:\SteamLibrary\steamapps\common\LittleNightmaresVRAlteredEchoes</GamePath>
    <MLPath>$(GamePath)\MelonLoader\net6</MLPath>
    <Il2CppAssemblies>$(GamePath)\MelonLoader\Il2CppAssemblies</Il2CppAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>$(MLPath)\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(MLPath)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MLPath)\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>$(MLPath)\Il2CppInterop.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.VRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.XRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>$(Il2CppAssemblies)\UnityEngine.SubsystemsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(Il2CppAssemblies)\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>$(Il2CppAssemblies)\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.XR.Management">
      <HintPath>$(Il2CppAssemblies)\Unity.XR.Management.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>$(Il2CppAssemblies)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(Il2CppAssemblies)\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(Il2CppAssemblies)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(Il2CppAssemblies)\Il2CppSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
